server:
  port: 18124

spring:
  application:
    name: aviasales-worker-node
  jms:
    listener:
      auto-startup: true

atomikos:
  properties.default-jta-timeout: 300
  log.dir: ./transaction_logs/worker_node_1/
  tm.unique.name: aviasalesWorkerNode1Tm
  xa.db:
    user: s367044
    password: rkemWfU26OYiwbkD
    serverName: localhost
    portNumber: "25432"
    databaseName: studs


camunda.bpm.client:
  async-response-timeout: 1000
  base-url: http://localhost:8080/engine-rest
  lock-duration: 60000