server:
  port: 18124

spring:
  application:
    name: aviasales-worker-node-1
  jms:
    listener:
      auto-startup: true

atomikos:
  log:
    dir: ./transaction_logs/worker_node_1/
  tm:
    unique:
      name: aviasalesWorkerNode1Tm
  xa:
    db:
      user: s367044
      password: rkemWfU26OYiwbkD
      serverName: localhost
      portNumber: "25432"
      databaseName: studs


camunda:
  bpm:
    database:
      # Worker НИКОГДА не должен трогать схему
      schema-update: false
    # Job Executor на Worker-узле должен быть включен
    job-execution:
      enabled: true
    # Админка на worker'е не нужна
    webapp:
      enabled: false