spring:
  datasource:
    driver-class-name: org.postgresql.Driver

    #    local
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:25432/studs}
#    username: ${SPRING_DATASOURCE_USERNAME:s367044}
#    password: ${SPRING_DATASOURCE_PASSWORD:rkemWfU26OYiwbkD}

    #    for helios
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/studs}
    username: ${SPRING_DATASOURCE_USERNAME:s367044}
    password: ${SPRING_DATASOURCE_PASSWORD:rkemWfU26OYiwbkD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        #        show-sql: true
        use_sql_comments: true
        default_schema: public
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true

  sql:
    init:
      mode: always



#logging:
#  level:
#    org:
#      hibernate:
#        type: debug

logging:
  level:
    org:
      hibernate:
        SQL: WARN
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 18123
