spring:
  application:
    name: blps

  datasource:
    xa:
      driver-class-name: org.postgresql.xa.PGXADataSource
#      url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/studs}
      username: ${SPRING_DATASOURCE_USERNAME:s367044}
      password: ${SPRING_DATASOURCE_PASSWORD:rkemWfU26OYiwbkD}
      serverName: localhost
      portNumber: 5432 # Вы используете порт 5432 в основном конфиге. Убедитесь, что он правильный.
      databaseName: studs

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.AtomikosJtaPlatform
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        use_sql_comments: true
        default_schema: public
    hibernate:
      ddl-auto: validate
    show-sql: true

  security:
    jaas:
      enabled: true
      app-name: XmlAuth
    user:
      password:
        encode: false

  activemq:
    broker-url-amqp: amqp://localhost:5672
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true


quartz:
  job-store-type: jdbc
  jdbc:
    initialize-schema: never
  properties:
    org:
      quartz:
        scheduler:
          instanceName: ClusteredScheduler
        threadPool:
          threadCount: 5
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          isClustered: true

  quartz:
    datasource:
      url: jdbc:postgresql://localhost:5432/studs
      username: s367044
      password: rkemWfU26OYiwbkD
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5

  jta:
    enabled: true
    log-dir: target/atomikos
    transaction-manager-id: myTm


camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    database:
      type: postgres
      schema-update: "false"
    transaction-manager-jta: true
    webapp:
      application-path: /camunda
#      port: 8080
    authorization:
      enabled: true
    job-execution:
      enabled: true
    metrics:
      enabled: false
    history-level: full
    process-engine-name: default
#    form:
#      enabled: true
#      resource-path: classpath:forms/
#    generic-properties:
#      properties:
#        historyTimeToLive: P1D


logging:
  level:
    org:
      hibernate:
        SQL: WARN
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    ticket.management: DEBUG

