spring:
  application:
    name: blps

  datasource:
    driver-class-name: org.postgresql.Driver

    #    local
    #    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:25432/studs}
    #    username: ${SPRING_DATASOURCE_USERNAME:s367044}
    #    password: ${SPRING_DATASOURCE_PASSWORD:rkemWfU26OYiwbkD}

    #    for helios
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/studs}
    username: ${SPRING_DATASOURCE_USERNAME:s367044}
    password: ${SPRING_DATASOURCE_PASSWORD:rkemWfU26OYiwbkD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        use_sql_comments: true
        default_schema: public
    hibernate:
      ddl-auto: validate
    show-sql: true

  security:
    jaas:
      enabled: true
      app-name: XmlAuth
    user:
      password:
        encode: false

  activemq:
    broker-url-amqp: amqp://localhost:5672
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  jms:
    listener:
      acknowledge-mode: auto
      auto-startup: true

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: ClusteredScheduler
            instanceId: AUTO
          threadPool:
            threadCount: 5
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreCMT
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            isClustered: true
            tablePrefix: QRTZ_
            txIsolationLevelSerializable: true

  jta:
    enabled: true
    log-dir: target/atomikos
    transaction-manager-id: myTm

logging:
  level:
    org:
      hibernate:
        SQL: WARN
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    ticket.management: DEBUG

