server:
  port: 18123

spring:
  application:
    name: aviasales-api-node
  jpa:
    hibernate:
      # Для API-узла при первом запуске! Потом можно вернуть 'validate'.
      ddl-auto: update
  jms:
    listener:
      auto-startup: false

atomikos:
  properties.default-jta-timeout: 300
  log-base-dir: ./transaction_logs/api_node/
  tm-unique-name: aviasalesApiNodeTm
  log:
    dir: ./transaction_logs/api_node/
  tm:
    unique:
      name: aviasalesApiNodeTm
  xa:
    db:
      user: s367044
      password: rkemWfU26OYiwbkD
      serverName: localhost
      portNumber: "25432"
      databaseName: studs
